/* ══ MOCK DATA (fallback quando não há dados reais) ════════════════════════ */
export const MOCK = {
  hoje: {
    kpis: {
      total:       { value: '74',  sub: '12 clientes únicos' },
      reservas:    { value: '8',   sub: 'link GetIn enviado' },
      fora:        { value: '5',   sub: 'vs. ontem', sm: true },
      pico:        { value: '19h', sub: 'Turno: Jantar', sm: true },
      aniversarios:{ value: '2',   sub: 'clientes únicos' },
      satisfacao:  { value: '88%', sub: '8 feedbacks (11% taxa)' },
      reclamacoes: { value: '1',   sub: 'vs. ontem' },
      programacao: { value: '12',  sub: 'Top: sexta' },
    },
    clientesUnicos: 12,
    satisfacao: 88,
    taxaFeedback: 11,
    reclamacoes: 1,
    programacaoCount: 12,
    progRanking: [
      { dia: 'sexta', count: 5 }, { dia: 'sabado', count: 4 }, { dia: 'quinta', count: 3 },
    ],
    diaMaisProcurado: { dia: 'sexta', count: 5 },
    linhaLabel: 'Hoje — Volume por hora',
    linha: [
      { dia: '10h', total: 3 }, { dia: '11h', total: 6 }, { dia: '12h', total: 14 },
      { dia: '13h', total: 19 }, { dia: '14h', total: 11 }, { dia: '15h', total: 7 },
      { dia: '16h', total: 5 }, { dia: '17h', total: 4 }, { dia: '18h', total: 8 },
      { dia: '19h', total: 12 }, { dia: '20h', total: 9 }, { dia: '21h', total: 6 }, { dia: '22h', total: 3 },
    ],
    donut: [
      { name: 'Reservas',     value: 8,  color: '#22C55E', pct: '11%' },
      { name: 'Programacao',  value: 12, color: '#3B82F6', pct: '16%' },
      { name: 'Cardapio',     value: 18, color: '#F97316', pct: '24%' },
      { name: 'Localizacao',  value: 10, color: '#8B5CF6', pct: '14%' },
      { name: 'Geral',        value: 20, color: '#6B7280', pct: '27%' },
      { name: 'Aniversario',  value: 3,  color: '#EC4899', pct: '4%' },
      { name: 'Reclamacao',   value: 3,  color: '#DC2626', pct: '4%' },
    ],
    barLabel: 'Distribuição por turno',
    barras: [
      { d: 'Almoco', al: 28, hh: 0, j: 0, f: 0 }, { d: 'Happy Hour', al: 0, hh: 16, j: 5, f: 0 }, { d: 'Jantar', al: 0, hh: 0, j: 25, f: 0 }, { d: 'Fora Horário', al: 0, hh: 0, j: 0, f: 5 },
    ],
    tableRows: [
      { id: '#001', h: '12:43', cli: 'Joao Silva',     tipo: 'Reservas',     turno: 'Almoco',      st: 'Positivo' },
      { id: '#002', h: '12:51', cli: 'Maria Santos',   tipo: 'Programacao',  turno: 'Almoco',      st: null },
      { id: '#003', h: '13:02', cli: 'Pedro Costa',    tipo: 'Localizacao',  turno: 'Almoco',      st: null },
      { id: '#004', h: '13:18', cli: 'Ana Lima',       tipo: 'Reservas',     turno: 'Almoco',      st: 'Positivo' },
      { id: '#005', h: '18:31', cli: 'Carlos Mendes',  tipo: 'Cardapio',     turno: 'Happy Hour',  st: 'Negativo' },
      { id: '#006', h: '19:45', cli: 'Lucia Ferreira', tipo: 'Reservas',     turno: 'Happy Hour',  st: 'Positivo' },
      { id: '#007', h: '20:02', cli: 'Roberto Alves',  tipo: 'Aniversario',  turno: 'Jantar',      st: 'Positivo' },
      { id: '#008', h: '21:19', cli: 'Fernanda Rocha', tipo: 'Geral',        turno: 'Jantar',      st: null },
    ],
    fidelizacao: {
      novos: 5, retornantes: 7, taxa: 58,
      evolucao: [{ dia: '18/03', novos: 5, retornantes: 7 }],
      frequentes: [
        { nome: 'Joao Silva', numero: '5511999001', diasContato: 3, count: 5, retornante: true },
        { nome: 'Maria Santos', numero: '5511999002', diasContato: 2, count: 3, retornante: true },
      ],
    },
  },
  semana: {
    kpis: {
      total:       { value: '406', sub: '89 clientes únicos' },
      reservas:    { value: '38',  sub: 'link GetIn enviado' },
      fora:        { value: '18',  sub: 'vs. semana anterior', sm: true },
      pico:        { value: '13h', sub: 'Turno: Almoco', sm: true },
      aniversarios:{ value: '7',   sub: 'clientes únicos' },
      satisfacao:  { value: '85%', sub: '34 feedbacks (8% taxa)' },
      reclamacoes: { value: '5',   sub: 'vs. semana anterior' },
      programacao: { value: '62',  sub: 'Top: sexta' },
    },
    clientesUnicos: 89,
    satisfacao: 85,
    taxaFeedback: 8,
    reclamacoes: 5,
    programacaoCount: 62,
    progRanking: [
      { dia: 'sexta', count: 18 }, { dia: 'sabado', count: 15 }, { dia: 'quinta', count: 12 },
      { dia: 'quarta', count: 8 }, { dia: 'domingo', count: 5 }, { dia: 'terca', count: 3 }, { dia: 'segunda', count: 1 },
    ],
    diaMaisProcurado: { dia: 'sexta', count: 18 },
    linhaLabel: 'Semana atual — Volume diário',
    linha: [
      { dia: 'Seg', total: 42 }, { dia: 'Ter', total: 38 }, { dia: 'Qua', total: 51 },
      { dia: 'Qui', total: 45 }, { dia: 'Sex', total: 67 }, { dia: 'Sab', total: 89 }, { dia: 'Dom', total: 74 },
    ],
    donut: [
      { name: 'Reservas',     value: 38,  color: '#22C55E', pct: '9%' },
      { name: 'Programacao',  value: 62,  color: '#3B82F6', pct: '15%' },
      { name: 'Cardapio',     value: 95,  color: '#F97316', pct: '23%' },
      { name: 'Localizacao',  value: 55,  color: '#8B5CF6', pct: '14%' },
      { name: 'Geral',        value: 120, color: '#6B7280', pct: '30%' },
      { name: 'Aniversario',  value: 18,  color: '#EC4899', pct: '4%' },
      { name: 'Reclamacao',   value: 18,  color: '#DC2626', pct: '5%' },
    ],
    barLabel: 'Almoço/HH x Jantar — 7 dias',
    barras: [
      { d: 'Seg', al: 10, hh: 12, j: 20, f: 3 }, { d: 'Ter', al: 8, hh: 10, j: 20, f: 2 }, { d: 'Qua', al: 12, hh: 13, j: 26, f: 4 },
      { d: 'Qui', al: 10, hh: 11, j: 24, f: 2 }, { d: 'Sex', al: 14, hh: 16, j: 37, f: 3 }, { d: 'Sab', al: 18, hh: 20, j: 51, f: 2 }, { d: 'Dom', al: 15, hh: 17, j: 42, f: 2 },
    ],
    tableRows: [
      { id: '#001', h: '12:43', cli: 'Joao Silva',     tipo: 'Reservas',     turno: 'Almoco',      st: 'Positivo' },
      { id: '#002', h: '12:51', cli: 'Maria Santos',   tipo: 'Programacao',  turno: 'Almoco',      st: null },
      { id: '#003', h: '13:02', cli: 'Pedro Costa',    tipo: 'Localizacao',  turno: 'Almoco',      st: null },
      { id: '#004', h: '19:18', cli: 'Ana Lima',       tipo: 'Aniversario',  turno: 'Happy Hour',  st: 'Positivo' },
    ],
    fidelizacao: {
      novos: 35, retornantes: 54, taxa: 61,
      evolucao: [
        { dia: '12/03', novos: 4, retornantes: 6 }, { dia: '13/03', novos: 5, retornantes: 7 },
        { dia: '14/03', novos: 3, retornantes: 8 }, { dia: '15/03', novos: 6, retornantes: 9 },
        { dia: '16/03', novos: 5, retornantes: 8 }, { dia: '17/03', novos: 7, retornantes: 10 },
        { dia: '18/03', novos: 5, retornantes: 6 },
      ],
      frequentes: [
        { nome: 'Joao Silva', numero: '5511999001', diasContato: 5, count: 12, retornante: true },
        { nome: 'Maria Santos', numero: '5511999002', diasContato: 4, count: 8, retornante: true },
        { nome: 'Pedro Costa', numero: '5511999003', diasContato: 3, count: 5, retornante: true },
      ],
    },
  },
  mes: {
    kpis: {
      total:       { value: '1840', sub: '312 clientes únicos' },
      reservas:    { value: '156',  sub: 'link GetIn enviado' },
      fora:        { value: '72',   sub: 'vs. mês anterior', sm: true },
      pico:        { value: '20h',  sub: 'Turno: Jantar', sm: true },
      aniversarios:{ value: '28',   sub: 'clientes únicos' },
      satisfacao:  { value: '82%',  sub: '147 feedbacks (8% taxa)' },
      reclamacoes: { value: '26',   sub: 'vs. mês anterior' },
      programacao: { value: '276',  sub: 'Top: sexta' },
    },
    clientesUnicos: 312,
    satisfacao: 82,
    taxaFeedback: 8,
    reclamacoes: 26,
    programacaoCount: 276,
    progRanking: [
      { dia: 'sexta', count: 72 }, { dia: 'sabado', count: 64 }, { dia: 'quinta', count: 52 },
      { dia: 'quarta', count: 38 }, { dia: 'domingo', count: 22 }, { dia: 'terca', count: 16 }, { dia: 'segunda', count: 12 },
    ],
    diaMaisProcurado: { dia: 'sexta', count: 72 },
    linhaLabel: 'Este mês — Volume semanal',
    linha: [
      { dia: 'Sem 1', total: 380 }, { dia: 'Sem 2', total: 420 },
      { dia: 'Sem 3', total: 452 }, { dia: 'Sem 4', total: 588 },
    ],
    donut: [
      { name: 'Reservas',     value: 156, color: '#22C55E', pct: '8%' },
      { name: 'Programacao',  value: 276, color: '#3B82F6', pct: '15%' },
      { name: 'Cardapio',     value: 423, color: '#F97316', pct: '23%' },
      { name: 'Localizacao',  value: 258, color: '#8B5CF6', pct: '14%' },
      { name: 'Geral',        value: 535, color: '#6B7280', pct: '29%' },
      { name: 'Aniversario',  value: 92,  color: '#EC4899', pct: '5%' },
      { name: 'Reclamacao',   value: 100, color: '#DC2626', pct: '6%' },
    ],
    barLabel: 'Almoço/HH x Jantar — mensal',
    barras: [
      { d: 'Sem 1', al: 75, hh: 90, j: 215, f: 12 }, { d: 'Sem 2', al: 80, hh: 100, j: 240, f: 15 },
      { d: 'Sem 3', al: 88, hh: 110, j: 254, f: 18 }, { d: 'Sem 4', al: 115, hh: 142, j: 331, f: 27 },
    ],
    tableRows: [
      { id: '#001', h: '12:43', cli: 'Joao Silva',     tipo: 'Reservas',    turno: 'Almoco',  st: 'Positivo' },
      { id: '#002', h: '20:51', cli: 'Maria Santos',   tipo: 'Programacao', turno: 'Jantar',  st: null },
    ],
    fidelizacao: {
      novos: 142, retornantes: 170, taxa: 55,
      evolucao: [
        { dia: 'Sem 1', novos: 30, retornantes: 38 }, { dia: 'Sem 2', novos: 35, retornantes: 42 },
        { dia: 'Sem 3', novos: 37, retornantes: 45 }, { dia: 'Sem 4', novos: 40, retornantes: 45 },
      ],
      frequentes: [
        { nome: 'Joao Silva', numero: '5511999001', diasContato: 12, count: 28, retornante: true },
        { nome: 'Maria Santos', numero: '5511999002', diasContato: 9, count: 18, retornante: true },
        { nome: 'Pedro Costa', numero: '5511999003', diasContato: 7, count: 14, retornante: true },
        { nome: 'Ana Lima', numero: '5511999004', diasContato: 5, count: 10, retornante: true },
      ],
    },
  },
}
